server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: ${USER_SERVICE_URI:http://localhost:8081}
              predicates:
                - Path=/api/users/**, /api/cards/**
            - id: order-service
              uri: ${ORDER_SERVICE_URI:http://localhost:8083}
              predicates:
                - Path=/api/orders/**
            - id: auth-service
              uri: ${AUTH_SERVICE_URI:http://localhost:8082}
              predicates:
                - Path=/api/auth/**

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-ms: 3600000

services:
  auth-service:
    url: ${AUTH_SERVICE_URI:http://localhost:8082}
  user-service:
    url: ${USER_SERVICE_URI:http://localhost:8081}

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    com.internship.api_gateway: DEBUG

